// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5ZBZtl7qYUszDwf874a9QkwiQOmJE28',
    appId: '1:307616880378:web:be71001408ffe83421db43',
    messagingSenderId: '307616880378',
    projectId: 'suaja-photobooth',
    authDomain: 'suaja-photobooth.firebaseapp.com',
    databaseURL: 'https://suaja-photobooth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suaja-photobooth.firebasestorage.app',
    measurementId: 'G-DJTS1W6Z65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtXHrW7UJVooNmYPQbG4d-1LQEQOJ-Js',
    appId: '1:307616880378:android:d263d7f1ebf7ee6721db43',
    messagingSenderId: '307616880378',
    projectId: 'suaja-photobooth',
    databaseURL: 'https://suaja-photobooth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suaja-photobooth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm59Hv487_OuRiMoB-U702ZvsjctRhr1o',
    appId: '1:307616880378:ios:5c6afba8ea7a236421db43',
    messagingSenderId: '307616880378',
    projectId: 'suaja-photobooth',
    databaseURL: 'https://suaja-photobooth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suaja-photobooth.firebasestorage.app',
    iosBundleId: 'com.suaja.suajaphotobooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm59Hv487_OuRiMoB-U702ZvsjctRhr1o',
    appId: '1:307616880378:ios:5c6afba8ea7a236421db43',
    messagingSenderId: '307616880378',
    projectId: 'suaja-photobooth',
    databaseURL: 'https://suaja-photobooth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suaja-photobooth.firebasestorage.app',
    iosBundleId: 'com.suaja.suajaphotobooth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5ZBZtl7qYUszDwf874a9QkwiQOmJE28',
    appId: '1:307616880378:web:c4b5d7e4f5af065e21db43',
    messagingSenderId: '307616880378',
    projectId: 'suaja-photobooth',
    authDomain: 'suaja-photobooth.firebaseapp.com',
    databaseURL: 'https://suaja-photobooth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'suaja-photobooth.firebasestorage.app',
    measurementId: 'G-TDH6T69K5X',
  );
}
